require("user.options")
require("user.keymap")
require("user.plugins")
-- These configure plugins, so must be after plugins
require("user.toggleterm")
require("user.lsp")
require("user.cmp")
require("user.treesitter")
require("user.keys")
require("user.notsosafelinks")
require("user.lualine")
require("user.gitsigns")
